
DROP TABLE IF EXISTS public.chapters CASCADE;
DROP TABLE IF EXISTS public.books CASCADE;

CREATE TABLE public.books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    author VARCHAR(100) NOT NULL,
    genre VARCHAR(50) NOT NULL,
    cover_image VARCHAR(255) DEFAULT 'default.jpg',
    synopsis TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.chapters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT REFERENCES public.books(id) ON DELETE CASCADE,
    chapter_number INT NOT NULL DEFAULT 1,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chapters ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read books" ON public.books FOR SELECT USING (true);
CREATE POLICY "Allow public insert books" ON public.books FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update books" ON public.books FOR UPDATE USING (true);
CREATE POLICY "Allow public delete books" ON public.books FOR DELETE USING (true);

CREATE POLICY "Allow public read chapters" ON public.chapters FOR SELECT USING (true);
CREATE POLICY "Allow public insert chapters" ON public.chapters FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update chapters" ON public.chapters FOR UPDATE USING (true);
CREATE POLICY "Allow public delete chapters" ON public.chapters FOR DELETE USING (true);

INSERT INTO public.books (id, title, author, genre, cover_image, synopsis) VALUES
(1, 'Langit yang Sama', 'Arkana Putra', 'Romance', 'cover_langit yang sama.jpg', 'Di bawah langit kota yang selalu redup, dua orang asing secara tak sengaja menemukan keterikatan yang membingungkan. Masing-masing membawa luka masa lalu yang enggan disembuhkan.'),
(2, 'Di Antara Kita', 'Nara Satria', 'Drama', 'cover_di Antara kita.jpe', 'Konflik persahabatan dan impian masa depan yang diuji ketika sebuah rahasia besar di antara mereka bertiga perlahan terungkap.'),
(3, 'Sebelum Langit Patah', 'Laras A.', 'Romance', 'cover_langit yang patah.jpe', 'Sebuah novel fiksi emosional tentang penerimaan, penyesalan, dan kesempatan kedua yang datang terlambat namun tetap berarti.'),
(4, 'Kamar 305', 'Raka Damar', 'Mystery', 'cover_kamar 305.jpg', 'Misteri kamar kos nomor 305 yang terkunci rapat selama 10 tahun dan menyimpan rahasia kelam kejadian tak terduga.'),
(5, 'pulang', 'Tara Adhitya', 'Slice of Life', 'cover_pulang.jpeg', 'Kisah hangat perjalanan seseorang kembali ke kampung halaman untuk menemukan arti rumah dan kedamaian diri.');

SELECT setval('books_id_seq', (SELECT MAX(id) FROM public.books));

INSERT INTO public.chapters (book_id, chapter_number, title, content) VALUES
(1, 1, 'Bab 1: Pertemuan di Kedai Kopi', 'Langit sore itu kembali memerah, seolah tahu bahwa hari ini bukan hari yang mudah bagiku. Aku berdiri di balkon, menatap jauh ke arah kota yang mulai diselimuti cahaya jingga. Angin lembut membawa aroma hujan yang belum turun, tapi sudah terasa di udara.\n\n"Kamu masih di sini?" suara itu akhirnya terdengar, memecah lamunanku.\n\nAku menoleh, dan di sana dia—sama seperti dulu, dengan senyum yang entah kenapa selalu bisa membuatku merasa tenang, meski dunia di sekitar kami tidak pernah benar-benar baik.\n\n"Iya," jawabku pelan. "Aku masih di sini."'),

(1, 2, 'Bab 2: Gerimis di Bulan November', 'Gerimis mulai menetes satu per satu membasahi kaca jendela kedai kopi tua di sudut jalan utama. Aroma espresso yang pekat memenuhi ruangan hangat ini.\n\n"Kenapa kamu memilih kembali?" tanya Clara pelan sambil mengaduk cangkir kapukinya.\n\nArka tersenyum tipis. "Karena beberapa tempat memang tidak pernah bisa benar-benar ditinggalkan, tak peduli seberapa jauh kita berusaha melarikan diri."'),

(1, 3, 'Bab 3: Bayangan yang Hilang', 'Malam semakin larut. Jalanan Bandung yang basah memantulkan lampu-lampu jalan berwarna kuning keemasan. Arka berjalan menyusuri trotoar dingin sendirian.\n\nSurat di dalam saku mantelnya terasa begitu berat. Rahasia yang disimpan selama tiga tahun ini akhirnya harus disampaikan.'),

(1, 4, 'Bab 4: Rahasia di Balik Catatan', 'Sebuah buku catatan bersampul cokelat lusuh ditemukan di bawah meja kayu kamar lama. Tulisan tangan di dalamnya menyibak tabir misteri yang selama ini tersembunyi.'),

(2, 1, 'Bab 1: Pagi di Koridor Sekolah', 'Pagi di SMA Taruna Persada selalu riuh. Suara gelak tawa dan langkah kaki beradu di koridor utama. Di sudut kantin, tiga cangkir teh manis mulai dingin.\n\nNara menatap dua sahabatnya yang diam membisu. "Kalian percaya kalau persahabatan kita bisa bertahan selamanya?"'),

(2, 2, 'Bab 2: Janji di Bawah Pohon Rindang', 'Di bawah pohon beringin tua samping lapangan basket, ketiga remaja itu mengukir nama mereka pada bangku kayu. Janji masa muda yang begitu manis.'),

(3, 1, 'Bab 1: Hujan Pertama di Musim Gugur', 'Ada beberapa hal yang tidak bisa diulang kembali: waktu yang berlalu, kata-kata yang terucap, dan kesempatan yang sia-sia. Laras menatap hujan yang mengguyur dedaunan di taman kota.'),

(4, 1, 'Bab 1: Ketukan Pukul 02:15 Malam', 'Jam dinding menunjukkan pukul 02:15 malam. Suara ketukan pelan di pintu kamar 305 terdengar kembali. Padahal kamar tersebut sudah dikosongkan sejak sekelompok mahasiswa lulus sepuluh tahun lalu...'),

(5, 1, 'Bab 1: Kereta Senja dan Rumah Tua', 'Kereta senja perlahan merapat di stasiun kecil ujung kota. Suara klakson kereta bersahut-sahutan dengan riuh para penjaja makanan. Setelah lima tahun merantau, akhirnya Tara melangkahkan kaki kembali ke rumah tua neneknya...');
